---
output:
  pdf_document: default
  word_document: default
  html_document: default
---
# BPTR: Bernstein Polynomial Temporal Realignment

## Statistical Model
$$\frac{Y_{ijk} - d_0}{d_1 - Y_{ijk}} = \beta_{ijk} \left\{\sum_{l=0}^d \theta_l b_{l,d}\left(\frac{t_{ijk} + \delta_{ij}}{{\underset{i,j}{\max}\left\{c_{ij}\right\}}}\right)\right\} \epsilon_{ijk},\ i=1,...,n;\ j=1,...,r_i;\ k=1,...,m_{ij};$$

* $\ln\left(\epsilon_{ijk}\right) | \sigma^2_{\epsilon} \stackrel{\text{iid}}{\sim} \text{N}\left(0, \sigma^2_{\epsilon}\right);$
* $c_{ij} = t_{ijm_{ij}} + a_{0ij} - a_1;$

* Progression parameters:
$$\ln\left(\beta_{ijk}\right) = \textbf{x}_{ijk}^{\text{T}}\boldsymbol{\gamma} + \zeta_{0i} + \zeta_{1ij},\ \zeta_{0i} | \sigma^2_{\zeta_0} \stackrel{\text{iid}}{\sim}\text{N}\left(0,\sigma^2_{\zeta_0}\right),\ \zeta_{1ij} | \sigma^2_{\zeta_1} \stackrel{\text{iid}}{\sim}\text{N}\left(0,\sigma^2_{\zeta_1}\right);$$

* Disease onset parameters:
$$\ln\left(\frac{a_{0ij} - \delta_{ij} - a_1}{\delta_{ij}}\right) = \textbf{z}_{ij}^{\text{T}}\boldsymbol{\eta} + \phi_{0i} + \phi_{1ij},\ \phi_{0i} | \sigma^2_{\phi_0} \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_{\phi_0}\right),\ \phi_{1ij} | \sigma^2_{\phi_1} \stackrel{\text{iid}}{\sim}\text{N}\left(0,\sigma^2_{\phi_1}\right);$$
* Bernstein polynomial regression parameters
$$\theta_0 \equiv 0;\ \theta_j = \theta_{j-1} + \psi_j,\ j=1,\hdots,d,$$ 
  * $\psi_1 = V_1$; 
  * $\psi_j = V_j\prod_{k=1}^{j-1}\left(1 - V_k\right)$ for $2 \leq j < d$; 
  * $\psi_d = \prod_{k=1}^{d-1}\left(1 - V_k\right)$;
  * $V_j | \alpha \stackrel{\text{iid}}{\sim} \text{Beta}\left(1, \alpha\right)$ for $j=1,...,d-1.$

## Prior Information
$\gamma_l \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_{\gamma}\right),\ l=1,...,p_x;$

* $p_x$: Length of $\textbf{x}_{ijk}$ vector (same for all $i,j,k$);

* Default setting: $\sigma^2_{\gamma} = 10,000.$

$\sigma^2_{\zeta_0} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\zeta_0}}, b_{\sigma^2_{\zeta_0}}\right);$

* Default setting: $a_{\sigma^2_{\zeta_0}} = 0.01$, $b_{\sigma^2_{\zeta_0}} = 0.01.$

$\sigma^2_{\zeta_1} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\zeta_1}}, b_{\sigma^2_{\zeta_1}}\right);$

* Default setting: $a_{\sigma^2_{\zeta_1}} = 0.01$, $b_{\sigma^2_{\zeta_1}} = 0.01.$

$\alpha \sim \text{Gamma}\left(a_{\alpha}, b_{\alpha}\right);$

* Default setting: $a_{\alpha} = 0.01$, $b_{\alpha} = 0.01.$

$\eta_l \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_{\eta}\right),\ j=1,...,p_z;$

* $p_z$: Length of $\textbf{z}_{ij}$ vector (same for all $i,j$);

* Default setting: $\sigma^2_{\eta} = 10,000.$

$\sigma^2_{\phi_0} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\phi_0}}, b_{\sigma^2_{\phi_0}}\right);$

* Default setting: $a_{\sigma^2_{\phi_0}} = 0.01$, $b_{\sigma^2_{\phi_0}} = 0.01.$

$\sigma^2_{\phi_1} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\phi_1}}, b_{\sigma^2_{\phi_1}}\right);$

* Default setting: $a_{\sigma^2_{\phi_1}} = 0.01$, $b_{\sigma^2_{\phi_1}} = 0.01.$
    
$\sigma^2_{\epsilon} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\epsilon}}, b_{\sigma^2_{\epsilon}}\right);$

* Default setting: $a_{\sigma^2_{\epsilon}} = 0.01$, $b_{\sigma^2_{\epsilon}} = 0.01.$

## Default Initial Values
* $\gamma_l = 0$ for all $l$;

* $\zeta_{0i} = 0$ for all $i$;

* $\sigma^2_{\zeta_0} = 0.01$;

* $\zeta_{1ij} = 0$ for all $i,j$;

* $\sigma^2_{\zeta_1} = 0.01$;

* $\alpha = 1.00$;

* $V_l = 0.50$ for all $l$;

* $\eta_l = 0$ for all $l$;

* $\phi_{0i} = 0$ for all $i$;

* $\sigma^2_{\phi_0} = 0.01$;

* $\sigma^2_{\phi_1} = 0.01$;

* $\delta_{ij} = \frac{a_{0ij} - a_1}{2}$;

* $\sigma^2_{\epsilon} = 0.01$.

## Notes
* $d$:  Selected degree of Bernstein polynomial;
* $a_{0ij}$:  Age of individual at first visit (specific to $j$);
* $a_1$:  Minimum age that any individual can develop the disease;
* $r_{i}$ must be $>1$ for all $i$;
* $m_{ij}$ must be $>1$ for all $i,j$.

