---
output:
  pdf_document: default
  html_document: default
  word_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# BPTR: Bernstein Polynomial Temporal Realignment

## BPTR_Example

```{r}
#########
#Packages
#########
library(BPTR)
library(matrixStats)
library(HDInterval)

##########
#Load Data
##########
url_path<-"https://raw.githubusercontent.com/warrenjl/BPTR/main/BPTR_Example/Simulated_Dataset.RData"
load(url(url_path))

##############
#Model Fitting
##############
set.seed(8234)

d<-3
results<-BPTR(mcmc_samples = 11000, 
              y_trans = sim_data$y_trans,
              r = sim_data$r, 
              m = sim_data$m, 
              t = sim_data$t_mat, 
              x = sim_data$x, 
              z = sim_data$z, 
              a0 = sim_data$a0, 
              a1 = sim_data$a1, 
              d = d,
              metrop_V = seq(0.005, 0.03, length.out = (d-1)),
              metrop_var_delta = rep(0.30^2, times = sum(sim_data$r)))

keep_set<-seq(1001,
              11000,
              10)

############################
#Severity Function Inference
############################
ds_time<-seq(sim_data$min_dis_time_select,
             sim_data$max_dis_time_select, 
             0.01)
z_ds<-matrix(NA,
             nrow = length(ds_time),
             ncol = (d+1))
for(j in 1:length(ds_time)){ 
   z_ds[j,]<-choose(d, c(0:d))*
             (ds_time[j]^c(0:d))*
             (1.00 - ds_time[j])^(d - c(0:d))  
   }

dis_sev<-matrix(NA,
                nrow = length(ds_time),
                ncol = length(keep_set))
for(j in 1:length(keep_set)){
   dis_sev[,j]<-exp(results$gamma[1, keep_set[j]])*c(z_ds%*%c(0.00, results$theta[,keep_set[j]]))
   } 

dis_sev_post_mean<-rowMeans(dis_sev)
dis_sev_post_median<-rowMedians(dis_sev)
dis_sev_quant<-rowQuantiles(dis_sev,
                            probs = c(0.025, 0.975))
dis_sev_hdi<-t(hdi(t(dis_sev),
                   credMass = 0.95))
dis_sev_post_mean_avg_bias<-mean(dis_sev_post_mean - sim_data$dis_sev)
dis_sev_post_median_avg_bias<-mean(dis_sev_post_median - sim_data$dis_sev)
dis_sev_quant_avg_ec<-mean(as.numeric((sim_data$dis_sev <= dis_sev_quant[,2]) & (sim_data$dis_sev >= dis_sev_quant[,1])))
dis_sev_hdi_avg_ec<-mean(as.numeric((sim_data$dis_sev <= dis_sev_hdi[,2]) & (sim_data$dis_sev >= dis_sev_hdi[,1])))

plot(sim_data$dis_sev, 
     type = "l",
     lwd = 2,
     col = "red")
lines(dis_sev_post_mean,
      lwd = 2)
lines(dis_sev_quant[,1],
      lwd = 2,
      lty = 2)
lines(dis_sev_quant[,2],
      lwd = 2,
      lty = 2)
```