// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BPTR
Rcpp::List BPTR(int mcmc_samples, arma::vec y_trans, arma::vec r, arma::vec m, arma::mat t, arma::mat x, arma::mat z, arma::vec a0, double a1, int d, arma::vec metrop_V, arma::vec metrop_var_delta, Rcpp::Nullable<double> sigma2_gamma_prior, Rcpp::Nullable<double> a_sigma2_zeta0_prior, Rcpp::Nullable<double> b_sigma2_zeta0_prior, Rcpp::Nullable<double> a_sigma2_zeta1_prior, Rcpp::Nullable<double> b_sigma2_zeta1_prior, Rcpp::Nullable<double> a_alpha_prior, Rcpp::Nullable<double> b_alpha_prior, Rcpp::Nullable<double> sigma2_eta_prior, Rcpp::Nullable<double> a_sigma2_phi0_prior, Rcpp::Nullable<double> b_sigma2_phi0_prior, Rcpp::Nullable<double> a_sigma2_phi1_prior, Rcpp::Nullable<double> b_sigma2_phi1_prior, Rcpp::Nullable<double> a_sigma2_epsilon_prior, Rcpp::Nullable<double> b_sigma2_epsilon_prior, Rcpp::Nullable<Rcpp::NumericVector> gamma_init, Rcpp::Nullable<Rcpp::NumericVector> zeta0_init, Rcpp::Nullable<double> sigma2_zeta0_init, Rcpp::Nullable<Rcpp::NumericVector> zeta1_init, Rcpp::Nullable<double> sigma2_zeta1_init, Rcpp::Nullable<Rcpp::NumericVector> theta_init, Rcpp::Nullable<Rcpp::NumericVector> V_init, Rcpp::Nullable<double> alpha_init, Rcpp::Nullable<Rcpp::NumericVector> delta_init, Rcpp::Nullable<Rcpp::NumericVector> eta_init, Rcpp::Nullable<Rcpp::NumericVector> phi0_init, Rcpp::Nullable<double> sigma2_phi0_init, Rcpp::Nullable<double> sigma2_phi1_init, Rcpp::Nullable<double> sigma2_epsilon_init);
RcppExport SEXP _BPTR_BPTR(SEXP mcmc_samplesSEXP, SEXP y_transSEXP, SEXP rSEXP, SEXP mSEXP, SEXP tSEXP, SEXP xSEXP, SEXP zSEXP, SEXP a0SEXP, SEXP a1SEXP, SEXP dSEXP, SEXP metrop_VSEXP, SEXP metrop_var_deltaSEXP, SEXP sigma2_gamma_priorSEXP, SEXP a_sigma2_zeta0_priorSEXP, SEXP b_sigma2_zeta0_priorSEXP, SEXP a_sigma2_zeta1_priorSEXP, SEXP b_sigma2_zeta1_priorSEXP, SEXP a_alpha_priorSEXP, SEXP b_alpha_priorSEXP, SEXP sigma2_eta_priorSEXP, SEXP a_sigma2_phi0_priorSEXP, SEXP b_sigma2_phi0_priorSEXP, SEXP a_sigma2_phi1_priorSEXP, SEXP b_sigma2_phi1_priorSEXP, SEXP a_sigma2_epsilon_priorSEXP, SEXP b_sigma2_epsilon_priorSEXP, SEXP gamma_initSEXP, SEXP zeta0_initSEXP, SEXP sigma2_zeta0_initSEXP, SEXP zeta1_initSEXP, SEXP sigma2_zeta1_initSEXP, SEXP theta_initSEXP, SEXP V_initSEXP, SEXP alpha_initSEXP, SEXP delta_initSEXP, SEXP eta_initSEXP, SEXP phi0_initSEXP, SEXP sigma2_phi0_initSEXP, SEXP sigma2_phi1_initSEXP, SEXP sigma2_epsilon_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type mcmc_samples(mcmc_samplesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_trans(y_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_V(metrop_VSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_var_delta(metrop_var_deltaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_gamma_prior(sigma2_gamma_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_zeta0_prior(a_sigma2_zeta0_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_zeta0_prior(b_sigma2_zeta0_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_zeta1_prior(a_sigma2_zeta1_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_zeta1_prior(b_sigma2_zeta1_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_alpha_prior(a_alpha_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_alpha_prior(b_alpha_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_eta_prior(sigma2_eta_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_phi0_prior(a_sigma2_phi0_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_phi0_prior(b_sigma2_phi0_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_phi1_prior(a_sigma2_phi1_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_phi1_prior(b_sigma2_phi1_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type a_sigma2_epsilon_prior(a_sigma2_epsilon_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type b_sigma2_epsilon_prior(b_sigma2_epsilon_priorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type zeta0_init(zeta0_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_zeta0_init(sigma2_zeta0_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type zeta1_init(zeta1_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_zeta1_init(sigma2_zeta1_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type V_init(V_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type delta_init(delta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type eta_init(eta_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type phi0_init(phi0_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_phi0_init(sigma2_phi0_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_phi1_init(sigma2_phi1_initSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type sigma2_epsilon_init(sigma2_epsilon_initSEXP);
    rcpp_result_gen = Rcpp::wrap(BPTR(mcmc_samples, y_trans, r, m, t, x, z, a0, a1, d, metrop_V, metrop_var_delta, sigma2_gamma_prior, a_sigma2_zeta0_prior, b_sigma2_zeta0_prior, a_sigma2_zeta1_prior, b_sigma2_zeta1_prior, a_alpha_prior, b_alpha_prior, sigma2_eta_prior, a_sigma2_phi0_prior, b_sigma2_phi0_prior, a_sigma2_phi1_prior, b_sigma2_phi1_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, gamma_init, zeta0_init, sigma2_zeta0_init, zeta1_init, sigma2_zeta1_init, theta_init, V_init, alpha_init, delta_init, eta_init, phi0_init, sigma2_phi0_init, sigma2_phi1_init, sigma2_epsilon_init));
    return rcpp_result_gen;
END_RCPP
}
// V_update
Rcpp::List V_update(arma::vec y_trans, arma::vec m, arma::mat x, int d, arma::vec mu_y_trans_old, arma::vec V_old, arma::vec theta_old, arma::vec psi_less_old, arma::vec psi_old, arma::vec full_theta_old, double alpha_old, arma::mat z_delta_old, double sigma2_epsilon_old, arma::vec metrop_V, arma::vec acctot_V);
RcppExport SEXP _BPTR_V_update(SEXP y_transSEXP, SEXP mSEXP, SEXP xSEXP, SEXP dSEXP, SEXP mu_y_trans_oldSEXP, SEXP V_oldSEXP, SEXP theta_oldSEXP, SEXP psi_less_oldSEXP, SEXP psi_oldSEXP, SEXP full_theta_oldSEXP, SEXP alpha_oldSEXP, SEXP z_delta_oldSEXP, SEXP sigma2_epsilon_oldSEXP, SEXP metrop_VSEXP, SEXP acctot_VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_trans(y_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_y_trans_old(mu_y_trans_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type V_old(V_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_old(theta_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type psi_less_old(psi_less_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type psi_old(psi_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type full_theta_old(full_theta_oldSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_old(alpha_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z_delta_old(z_delta_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon_old(sigma2_epsilon_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_V(metrop_VSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type acctot_V(acctot_VSEXP);
    rcpp_result_gen = Rcpp::wrap(V_update(y_trans, m, x, d, mu_y_trans_old, V_old, theta_old, psi_less_old, psi_old, full_theta_old, alpha_old, z_delta_old, sigma2_epsilon_old, metrop_V, acctot_V));
    return rcpp_result_gen;
END_RCPP
}
// alpha_update
double alpha_update(int d, double a_alpha, double b_alpha, arma::vec V);
RcppExport SEXP _BPTR_alpha_update(SEXP dSEXP, SEXP a_alphaSEXP, SEXP b_alphaSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type a_alpha(a_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type b_alpha(b_alphaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(alpha_update(d, a_alpha, b_alpha, V));
    return rcpp_result_gen;
END_RCPP
}
// delta_update
Rcpp::List delta_update(arma::vec y_trans, int sum_r, arma::vec m, arma::mat t, arma::mat z, arma::vec c, int d, arma::vec a0, arma::vec max_a1_a2, arma::vec choose_vec, Rcpp::IntegerVector power1, Rcpp::IntegerVector power2, Rcpp::IntegerVector phi0_pointer, arma::vec mu_y_trans_old, arma::vec theta, arma::vec full_theta, arma::vec delta_old, arma::vec delta_trans_old, arma::mat z_delta_old, arma::vec eta_old, arma::vec phi0_old, double sigma2_phi1_old, double sigma2_epsilon_old, arma::vec metrop_var_delta, arma::vec acctot_delta);
RcppExport SEXP _BPTR_delta_update(SEXP y_transSEXP, SEXP sum_rSEXP, SEXP mSEXP, SEXP tSEXP, SEXP zSEXP, SEXP cSEXP, SEXP dSEXP, SEXP a0SEXP, SEXP max_a1_a2SEXP, SEXP choose_vecSEXP, SEXP power1SEXP, SEXP power2SEXP, SEXP phi0_pointerSEXP, SEXP mu_y_trans_oldSEXP, SEXP thetaSEXP, SEXP full_thetaSEXP, SEXP delta_oldSEXP, SEXP delta_trans_oldSEXP, SEXP z_delta_oldSEXP, SEXP eta_oldSEXP, SEXP phi0_oldSEXP, SEXP sigma2_phi1_oldSEXP, SEXP sigma2_epsilon_oldSEXP, SEXP metrop_var_deltaSEXP, SEXP acctot_deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_trans(y_transSEXP);
    Rcpp::traits::input_parameter< int >::type sum_r(sum_rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type max_a1_a2(max_a1_a2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type choose_vec(choose_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type power1(power1SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type power2(power2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type phi0_pointer(phi0_pointerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_y_trans_old(mu_y_trans_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type full_theta(full_thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_old(delta_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_trans_old(delta_trans_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z_delta_old(z_delta_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta_old(eta_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi0_old(phi0_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_phi1_old(sigma2_phi1_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon_old(sigma2_epsilon_oldSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type metrop_var_delta(metrop_var_deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type acctot_delta(acctot_deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(delta_update(y_trans, sum_r, m, t, z, c, d, a0, max_a1_a2, choose_vec, power1, power2, phi0_pointer, mu_y_trans_old, theta, full_theta, delta_old, delta_trans_old, z_delta_old, eta_old, phi0_old, sigma2_phi1_old, sigma2_epsilon_old, metrop_var_delta, acctot_delta));
    return rcpp_result_gen;
END_RCPP
}
// eta_update
arma::vec eta_update(arma::mat z_trans, arma::mat ztz, arma::mat one_star2, int p_z, double sigma2_eta, arma::vec delta_trans, arma::vec phi0_old, double sigma2_phi1_old);
RcppExport SEXP _BPTR_eta_update(SEXP z_transSEXP, SEXP ztzSEXP, SEXP one_star2SEXP, SEXP p_zSEXP, SEXP sigma2_etaSEXP, SEXP delta_transSEXP, SEXP phi0_oldSEXP, SEXP sigma2_phi1_oldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type z_trans(z_transSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type ztz(ztzSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star2(one_star2SEXP);
    Rcpp::traits::input_parameter< int >::type p_z(p_zSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_eta(sigma2_etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_trans(delta_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi0_old(phi0_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_phi1_old(sigma2_phi1_oldSEXP);
    rcpp_result_gen = Rcpp::wrap(eta_update(z_trans, ztz, one_star2, p_z, sigma2_eta, delta_trans, phi0_old, sigma2_phi1_old));
    return rcpp_result_gen;
END_RCPP
}
// gamma_update
Rcpp::List gamma_update(arma::vec y_trans, arma::mat x, arma::mat x_trans, arma::mat xtx, int p_x, double sigma2_gamma, arma::vec mu_y_trans, arma::vec gamma_old, double sigma2_epsilon_old);
RcppExport SEXP _BPTR_gamma_update(SEXP y_transSEXP, SEXP xSEXP, SEXP x_transSEXP, SEXP xtxSEXP, SEXP p_xSEXP, SEXP sigma2_gammaSEXP, SEXP mu_y_transSEXP, SEXP gamma_oldSEXP, SEXP sigma2_epsilon_oldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_trans(y_transSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x_trans(x_transSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xtx(xtxSEXP);
    Rcpp::traits::input_parameter< int >::type p_x(p_xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_gamma(sigma2_gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_y_trans(mu_y_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma_old(gamma_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon_old(sigma2_epsilon_oldSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_update(y_trans, x, x_trans, xtx, p_x, sigma2_gamma, mu_y_trans, gamma_old, sigma2_epsilon_old));
    return rcpp_result_gen;
END_RCPP
}
// neg_two_loglike_update
double neg_two_loglike_update(arma::vec y_trans, arma::vec m, arma::vec mu_y_trans, double sigma2_epsilon);
RcppExport SEXP _BPTR_neg_two_loglike_update(SEXP y_transSEXP, SEXP mSEXP, SEXP mu_y_transSEXP, SEXP sigma2_epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_trans(y_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_y_trans(mu_y_transSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon(sigma2_epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(neg_two_loglike_update(y_trans, m, mu_y_trans, sigma2_epsilon));
    return rcpp_result_gen;
END_RCPP
}
// phi0_update
arma::vec phi0_update(arma::mat z, arma::mat one_star2_trans, arma::mat one_star2_t_one_star2, int n, arma::vec delta_trans, arma::vec eta, double sigma2_phi0_old, double sigma2_phi1_old);
RcppExport SEXP _BPTR_phi0_update(SEXP zSEXP, SEXP one_star2_transSEXP, SEXP one_star2_t_one_star2SEXP, SEXP nSEXP, SEXP delta_transSEXP, SEXP etaSEXP, SEXP sigma2_phi0_oldSEXP, SEXP sigma2_phi1_oldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star2_trans(one_star2_transSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star2_t_one_star2(one_star2_t_one_star2SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_trans(delta_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_phi0_old(sigma2_phi0_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_phi1_old(sigma2_phi1_oldSEXP);
    rcpp_result_gen = Rcpp::wrap(phi0_update(z, one_star2_trans, one_star2_t_one_star2, n, delta_trans, eta, sigma2_phi0_old, sigma2_phi1_old));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_epsilon_update
double sigma2_epsilon_update(arma::vec y_trans, arma::vec m, arma::vec mu_y_trans, double a_sigma2_epsilon, double b_sigma2_epsilon);
RcppExport SEXP _BPTR_sigma2_epsilon_update(SEXP y_transSEXP, SEXP mSEXP, SEXP mu_y_transSEXP, SEXP a_sigma2_epsilonSEXP, SEXP b_sigma2_epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_trans(y_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_y_trans(mu_y_transSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2_epsilon(a_sigma2_epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2_epsilon(b_sigma2_epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_epsilon_update(y_trans, m, mu_y_trans, a_sigma2_epsilon, b_sigma2_epsilon));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_phi0_update
double sigma2_phi0_update(int n, double a_sigma2_phi0, double b_sigma2_phi0, arma::vec phi0);
RcppExport SEXP _BPTR_sigma2_phi0_update(SEXP nSEXP, SEXP a_sigma2_phi0SEXP, SEXP b_sigma2_phi0SEXP, SEXP phi0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2_phi0(a_sigma2_phi0SEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2_phi0(b_sigma2_phi0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi0(phi0SEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_phi0_update(n, a_sigma2_phi0, b_sigma2_phi0, phi0));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_phi1_update
double sigma2_phi1_update(int sum_r, arma::mat z, arma::mat one_star2, double a_sigma2_phi1, double b_sigma2_phi1, arma::vec delta_trans, arma::vec eta, arma::vec phi0);
RcppExport SEXP _BPTR_sigma2_phi1_update(SEXP sum_rSEXP, SEXP zSEXP, SEXP one_star2SEXP, SEXP a_sigma2_phi1SEXP, SEXP b_sigma2_phi1SEXP, SEXP delta_transSEXP, SEXP etaSEXP, SEXP phi0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type sum_r(sum_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star2(one_star2SEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2_phi1(a_sigma2_phi1SEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2_phi1(b_sigma2_phi1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_trans(delta_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi0(phi0SEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_phi1_update(sum_r, z, one_star2, a_sigma2_phi1, b_sigma2_phi1, delta_trans, eta, phi0));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_zeta0_update
double sigma2_zeta0_update(int n, double a_sigma2_zeta0, double b_sigma2_zeta0, arma::vec zeta0);
RcppExport SEXP _BPTR_sigma2_zeta0_update(SEXP nSEXP, SEXP a_sigma2_zeta0SEXP, SEXP b_sigma2_zeta0SEXP, SEXP zeta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2_zeta0(a_sigma2_zeta0SEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2_zeta0(b_sigma2_zeta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type zeta0(zeta0SEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_zeta0_update(n, a_sigma2_zeta0, b_sigma2_zeta0, zeta0));
    return rcpp_result_gen;
END_RCPP
}
// sigma2_zeta1_update
double sigma2_zeta1_update(int sum_r, double a_sigma2_zeta1, double b_sigma2_zeta1, arma::vec zeta1);
RcppExport SEXP _BPTR_sigma2_zeta1_update(SEXP sum_rSEXP, SEXP a_sigma2_zeta1SEXP, SEXP b_sigma2_zeta1SEXP, SEXP zeta1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type sum_r(sum_rSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma2_zeta1(a_sigma2_zeta1SEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma2_zeta1(b_sigma2_zeta1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type zeta1(zeta1SEXP);
    rcpp_result_gen = Rcpp::wrap(sigma2_zeta1_update(sum_r, a_sigma2_zeta1, b_sigma2_zeta1, zeta1));
    return rcpp_result_gen;
END_RCPP
}
// zeta0_update
Rcpp::List zeta0_update(arma::vec y_trans, int n, arma::mat one_star0, arma::mat one_star0_trans, arma::mat one_star0_t_one_star0, arma::vec mu_y_trans, arma::vec zeta0_old, double sigma2_zeta0_old, double sigma2_epsilon_old);
RcppExport SEXP _BPTR_zeta0_update(SEXP y_transSEXP, SEXP nSEXP, SEXP one_star0SEXP, SEXP one_star0_transSEXP, SEXP one_star0_t_one_star0SEXP, SEXP mu_y_transSEXP, SEXP zeta0_oldSEXP, SEXP sigma2_zeta0_oldSEXP, SEXP sigma2_epsilon_oldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_trans(y_transSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star0(one_star0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star0_trans(one_star0_transSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star0_t_one_star0(one_star0_t_one_star0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_y_trans(mu_y_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type zeta0_old(zeta0_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_zeta0_old(sigma2_zeta0_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon_old(sigma2_epsilon_oldSEXP);
    rcpp_result_gen = Rcpp::wrap(zeta0_update(y_trans, n, one_star0, one_star0_trans, one_star0_t_one_star0, mu_y_trans, zeta0_old, sigma2_zeta0_old, sigma2_epsilon_old));
    return rcpp_result_gen;
END_RCPP
}
// zeta1_update
Rcpp::List zeta1_update(arma::vec y_trans, int sum_r, arma::mat one_star1, arma::mat one_star1_trans, arma::mat one_star1_t_one_star1, arma::vec mu_y_trans, arma::vec zeta1_old, double sigma2_zeta1_old, double sigma2_epsilon_old);
RcppExport SEXP _BPTR_zeta1_update(SEXP y_transSEXP, SEXP sum_rSEXP, SEXP one_star1SEXP, SEXP one_star1_transSEXP, SEXP one_star1_t_one_star1SEXP, SEXP mu_y_transSEXP, SEXP zeta1_oldSEXP, SEXP sigma2_zeta1_oldSEXP, SEXP sigma2_epsilon_oldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y_trans(y_transSEXP);
    Rcpp::traits::input_parameter< int >::type sum_r(sum_rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star1(one_star1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star1_trans(one_star1_transSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type one_star1_t_one_star1(one_star1_t_one_star1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu_y_trans(mu_y_transSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type zeta1_old(zeta1_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_zeta1_old(sigma2_zeta1_oldSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_epsilon_old(sigma2_epsilon_oldSEXP);
    rcpp_result_gen = Rcpp::wrap(zeta1_update(y_trans, sum_r, one_star1, one_star1_trans, one_star1_t_one_star1, mu_y_trans, zeta1_old, sigma2_zeta1_old, sigma2_epsilon_old));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BPTR_BPTR", (DL_FUNC) &_BPTR_BPTR, 40},
    {"_BPTR_V_update", (DL_FUNC) &_BPTR_V_update, 15},
    {"_BPTR_alpha_update", (DL_FUNC) &_BPTR_alpha_update, 4},
    {"_BPTR_delta_update", (DL_FUNC) &_BPTR_delta_update, 25},
    {"_BPTR_eta_update", (DL_FUNC) &_BPTR_eta_update, 8},
    {"_BPTR_gamma_update", (DL_FUNC) &_BPTR_gamma_update, 9},
    {"_BPTR_neg_two_loglike_update", (DL_FUNC) &_BPTR_neg_two_loglike_update, 4},
    {"_BPTR_phi0_update", (DL_FUNC) &_BPTR_phi0_update, 8},
    {"_BPTR_sigma2_epsilon_update", (DL_FUNC) &_BPTR_sigma2_epsilon_update, 5},
    {"_BPTR_sigma2_phi0_update", (DL_FUNC) &_BPTR_sigma2_phi0_update, 4},
    {"_BPTR_sigma2_phi1_update", (DL_FUNC) &_BPTR_sigma2_phi1_update, 8},
    {"_BPTR_sigma2_zeta0_update", (DL_FUNC) &_BPTR_sigma2_zeta0_update, 4},
    {"_BPTR_sigma2_zeta1_update", (DL_FUNC) &_BPTR_sigma2_zeta1_update, 4},
    {"_BPTR_zeta0_update", (DL_FUNC) &_BPTR_zeta0_update, 9},
    {"_BPTR_zeta1_update", (DL_FUNC) &_BPTR_zeta1_update, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_BPTR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
