# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BETR <- function(mcmc_samples, y_trans, m, t, x, z, a0, a2, d, metrop_V, metrop_var_delta, a1_opt = NULL, sigma2_gamma_prior = NULL, a_sigma2_zeta_prior = NULL, b_sigma2_zeta_prior = NULL, a_alpha_prior = NULL, b_alpha_prior = NULL, sigma2_eta_prior = NULL, a_sigma2_phi_prior = NULL, b_sigma2_phi_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, gamma_init = NULL, zeta_init = NULL, sigma2_zeta_init = NULL, theta_init = NULL, V_init = NULL, alpha_init = NULL, delta_init = NULL, eta_init = NULL, sigma2_phi_init = NULL, sigma2_epsilon_init = NULL) {
    .Call(`_BETR_BETR`, mcmc_samples, y_trans, m, t, x, z, a0, a2, d, metrop_V, metrop_var_delta, a1_opt, sigma2_gamma_prior, a_sigma2_zeta_prior, b_sigma2_zeta_prior, a_alpha_prior, b_alpha_prior, sigma2_eta_prior, a_sigma2_phi_prior, b_sigma2_phi_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, gamma_init, zeta_init, sigma2_zeta_init, theta_init, V_init, alpha_init, delta_init, eta_init, sigma2_phi_init, sigma2_epsilon_init)
}

V_update <- function(y_trans, m, x, one_star, d, mu_y_trans_old, gamma, zeta, V_old, theta_old, psi_less_old, psi_old, full_theta_old, alpha_old, z_delta_old, sigma2_epsilon_old, metrop_V, acctot_V) {
    .Call(`_BETR_V_update`, y_trans, m, x, one_star, d, mu_y_trans_old, gamma, zeta, V_old, theta_old, psi_less_old, psi_old, full_theta_old, alpha_old, z_delta_old, sigma2_epsilon_old, metrop_V, acctot_V)
}

alpha_update <- function(d, a_alpha, b_alpha, V) {
    .Call(`_BETR_alpha_update`, d, a_alpha, b_alpha, V)
}

delta_update <- function(y_trans, n, m, t, z, c, d, a0, max_a1_a2, choose_vec, power1, power2, mu_y_trans_old, theta, full_theta, delta_old, delta_trans_old, z_delta_old, eta_old, sigma2_phi_old, sigma2_epsilon_old, metrop_var_delta, acctot_delta) {
    .Call(`_BETR_delta_update`, y_trans, n, m, t, z, c, d, a0, max_a1_a2, choose_vec, power1, power2, mu_y_trans_old, theta, full_theta, delta_old, delta_trans_old, z_delta_old, eta_old, sigma2_phi_old, sigma2_epsilon_old, metrop_var_delta, acctot_delta)
}

eta_update <- function(z_trans, ztz, p_z, sigma2_eta, delta_trans, sigma2_phi_old) {
    .Call(`_BETR_eta_update`, z_trans, ztz, p_z, sigma2_eta, delta_trans, sigma2_phi_old)
}

gamma_update <- function(y_trans, x, x_trans, xtx, p_x, sigma2_gamma, mu_y_trans, gamma_old, sigma2_epsilon_old) {
    .Call(`_BETR_gamma_update`, y_trans, x, x_trans, xtx, p_x, sigma2_gamma, mu_y_trans, gamma_old, sigma2_epsilon_old)
}

neg_two_loglike_update <- function(y_trans, m, mu_y_trans, sigma2_epsilon) {
    .Call(`_BETR_neg_two_loglike_update`, y_trans, m, mu_y_trans, sigma2_epsilon)
}

sigma2_epsilon_update <- function(y_trans, m, mu_y_trans, a_sigma2_epsilon, b_sigma2_epsilon) {
    .Call(`_BETR_sigma2_epsilon_update`, y_trans, m, mu_y_trans, a_sigma2_epsilon, b_sigma2_epsilon)
}

sigma2_phi_update <- function(n, z, a_sigma2_phi, b_sigma2_phi, delta_trans, eta) {
    .Call(`_BETR_sigma2_phi_update`, n, z, a_sigma2_phi, b_sigma2_phi, delta_trans, eta)
}

sigma2_zeta_update <- function(n, a_sigma2_zeta, b_sigma2_zeta, zeta) {
    .Call(`_BETR_sigma2_zeta_update`, n, a_sigma2_zeta, b_sigma2_zeta, zeta)
}

zeta_update <- function(y_trans, n, one_star, one_star_trans, one_star_t_one_star, mu_y_trans, zeta_old, sigma2_zeta_old, sigma2_epsilon_old) {
    .Call(`_BETR_zeta_update`, y_trans, n, one_star, one_star_trans, one_star_t_one_star, mu_y_trans, zeta_old, sigma2_zeta_old, sigma2_epsilon_old)
}

