# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BETR <- function(mcmc_samples, y_trans, r, m, t, x, z, a0, a2, d, metrop_V, metrop_var_delta, a1_opt = NULL, sigma2_gamma_prior = NULL, a_sigma2_zeta0_prior = NULL, b_sigma2_zeta0_prior = NULL, a_sigma2_zeta1_prior = NULL, b_sigma2_zeta1_prior = NULL, a_alpha_prior = NULL, b_alpha_prior = NULL, sigma2_eta_prior = NULL, a_sigma2_phi0_prior = NULL, b_sigma2_phi0_prior = NULL, a_sigma2_phi1_prior = NULL, b_sigma2_phi1_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, gamma_init = NULL, zeta0_init = NULL, sigma2_zeta0_init = NULL, zeta1_init = NULL, sigma2_zeta1_init = NULL, theta_init = NULL, V_init = NULL, alpha_init = NULL, delta_init = NULL, eta_init = NULL, phi0_init = NULL, sigma2_phi0_init = NULL, sigma2_phi1_init = NULL, sigma2_epsilon_init = NULL) {
    .Call(`_BETR_BETR`, mcmc_samples, y_trans, r, m, t, x, z, a0, a2, d, metrop_V, metrop_var_delta, a1_opt, sigma2_gamma_prior, a_sigma2_zeta0_prior, b_sigma2_zeta0_prior, a_sigma2_zeta1_prior, b_sigma2_zeta1_prior, a_alpha_prior, b_alpha_prior, sigma2_eta_prior, a_sigma2_phi0_prior, b_sigma2_phi0_prior, a_sigma2_phi1_prior, b_sigma2_phi1_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, gamma_init, zeta0_init, sigma2_zeta0_init, zeta1_init, sigma2_zeta1_init, theta_init, V_init, alpha_init, delta_init, eta_init, phi0_init, sigma2_phi0_init, sigma2_phi1_init, sigma2_epsilon_init)
}

V_update <- function(y_trans, m, x, d, mu_y_trans_old, V_old, theta_old, psi_less_old, psi_old, full_theta_old, alpha_old, z_delta_old, sigma2_epsilon_old, metrop_V, acctot_V) {
    .Call(`_BETR_V_update`, y_trans, m, x, d, mu_y_trans_old, V_old, theta_old, psi_less_old, psi_old, full_theta_old, alpha_old, z_delta_old, sigma2_epsilon_old, metrop_V, acctot_V)
}

alpha_update <- function(d, a_alpha, b_alpha, V) {
    .Call(`_BETR_alpha_update`, d, a_alpha, b_alpha, V)
}

delta_update <- function(y_trans, sum_r, m, t, z, c, d, a0, max_a1_a2, choose_vec, power1, power2, phi0_pointer, mu_y_trans_old, theta, full_theta, delta_old, delta_trans_old, z_delta_old, eta_old, phi0_old, sigma2_phi1_old, sigma2_epsilon_old, metrop_var_delta, acctot_delta) {
    .Call(`_BETR_delta_update`, y_trans, sum_r, m, t, z, c, d, a0, max_a1_a2, choose_vec, power1, power2, phi0_pointer, mu_y_trans_old, theta, full_theta, delta_old, delta_trans_old, z_delta_old, eta_old, phi0_old, sigma2_phi1_old, sigma2_epsilon_old, metrop_var_delta, acctot_delta)
}

eta_update <- function(z_trans, ztz, one_star2, p_z, sigma2_eta, delta_trans, phi0_old, sigma2_phi1_old) {
    .Call(`_BETR_eta_update`, z_trans, ztz, one_star2, p_z, sigma2_eta, delta_trans, phi0_old, sigma2_phi1_old)
}

gamma_update <- function(y_trans, x, x_trans, xtx, p_x, sigma2_gamma, mu_y_trans, gamma_old, sigma2_epsilon_old) {
    .Call(`_BETR_gamma_update`, y_trans, x, x_trans, xtx, p_x, sigma2_gamma, mu_y_trans, gamma_old, sigma2_epsilon_old)
}

neg_two_loglike_update <- function(y_trans, m, mu_y_trans, sigma2_epsilon) {
    .Call(`_BETR_neg_two_loglike_update`, y_trans, m, mu_y_trans, sigma2_epsilon)
}

phi0_update <- function(z, one_star2_trans, one_star2_t_one_star2, n, delta_trans, eta, sigma2_phi0_old, sigma2_phi1_old) {
    .Call(`_BETR_phi0_update`, z, one_star2_trans, one_star2_t_one_star2, n, delta_trans, eta, sigma2_phi0_old, sigma2_phi1_old)
}

sigma2_epsilon_update <- function(y_trans, m, mu_y_trans, a_sigma2_epsilon, b_sigma2_epsilon) {
    .Call(`_BETR_sigma2_epsilon_update`, y_trans, m, mu_y_trans, a_sigma2_epsilon, b_sigma2_epsilon)
}

sigma2_phi0_update <- function(n, a_sigma2_phi0, b_sigma2_phi0, phi0) {
    .Call(`_BETR_sigma2_phi0_update`, n, a_sigma2_phi0, b_sigma2_phi0, phi0)
}

sigma2_phi1_update <- function(sum_r, z, one_star2, a_sigma2_phi1, b_sigma2_phi1, delta_trans, eta, phi0) {
    .Call(`_BETR_sigma2_phi1_update`, sum_r, z, one_star2, a_sigma2_phi1, b_sigma2_phi1, delta_trans, eta, phi0)
}

sigma2_zeta0_update <- function(n, a_sigma2_zeta0, b_sigma2_zeta0, zeta0) {
    .Call(`_BETR_sigma2_zeta0_update`, n, a_sigma2_zeta0, b_sigma2_zeta0, zeta0)
}

sigma2_zeta1_update <- function(sum_r, a_sigma2_zeta1, b_sigma2_zeta1, zeta1) {
    .Call(`_BETR_sigma2_zeta1_update`, sum_r, a_sigma2_zeta1, b_sigma2_zeta1, zeta1)
}

zeta0_update <- function(y_trans, n, one_star0, one_star0_trans, one_star0_t_one_star0, mu_y_trans, zeta0_old, sigma2_zeta0_old, sigma2_epsilon_old) {
    .Call(`_BETR_zeta0_update`, y_trans, n, one_star0, one_star0_trans, one_star0_t_one_star0, mu_y_trans, zeta0_old, sigma2_zeta0_old, sigma2_epsilon_old)
}

zeta1_update <- function(y_trans, sum_r, one_star1, one_star1_trans, one_star1_t_one_star1, mu_y_trans, zeta1_old, sigma2_zeta1_old, sigma2_epsilon_old) {
    .Call(`_BETR_zeta1_update`, y_trans, sum_r, one_star1, one_star1_trans, one_star1_t_one_star1, mu_y_trans, zeta1_old, sigma2_zeta1_old, sigma2_epsilon_old)
}

